from transformers.configuration_utils import PretrainedConfig


class SegmentFreeBertConfig(PretrainedConfig):
    model_type = "segmentfreebert"

    def __init__(
        self,
        hidden_size=768,
        num_hidden_layers=12,
        num_attention_heads=12,
        intermediate_size=3072,
        hidden_act="gelu",
        hidden_dropout_prob=0.1,
        attention_probs_dropout_prob=0.1,
        max_position_embeddings=512,
        max_length=512,
        type_vocab_size=1,
        initializer_range=0.02,
        layer_norm_eps=1e-12,
        position_embedding_type="absolute",
        use_cache=True,
        classifier_dropout=None,
        **kwargs,
    ):
        pad_token_id = kwargs.pop("pad_token_id", 0)

        # Gọi hàm super() với pad_token_id đã được xử lý
        super().__init__(pad_token_id=pad_token_id, **kwargs)

        self.hidden_size = hidden_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.hidden_act = hidden_act
        self.intermediate_size = intermediate_size
        self.hidden_dropout_prob = hidden_dropout_prob
        self.attention_probs_dropout_prob = attention_probs_dropout_prob
        self.max_position_embeddings = max_position_embeddings
        self.max_length = max_length
        self.type_vocab_size = type_vocab_size
        self.initializer_range = initializer_range
        self.layer_norm_eps = layer_norm_eps
        self.position_embedding_type = position_embedding_type
        self.use_cache = use_cache
        self.classifier_dropout = classifier_dropout

        self.pad_token = "<pad>"
        self.cls_token = "<cls>"
        self.empty_token = "<empty>"
        self.mask_token = "<mask>"
        self.unk_token = "<unk>"

        self.specials = [self.pad_token, self.cls_token, self.empty_token, self.mask_token, self.unk_token]

        self.pad_token_id = 0
        self.cls_token_id = 1
        self.empty_token_id = 2
        self.mask_token_id = 3
        self.unk_token_id = 4

        self.special_ids = [self.pad_token_id, self.cls_token_id, self.empty_token_id, self.mask_token_id, self.unk_token_id]

        # Full-syllable (morpheme) vocabulary for the segmentation-free tokenizer, collected by
        # collect-Vietnamese.py into configs/morphemes.json. Every token is embedded here so the
        # config is self-contained, matching the convention of the other *_bert_config.py files.
        self.morphemes = [
            "nghiền", "mống", "chẹo", "móp", "nằn", "chém", "trám", "bơm", "tân", "tếu", "nga", "núp", "xài", "hờ",
            "về", "nhày", "nấn", "cút", "cúc", "kiêm", "nếm", "nhâu", "ngỗng", "diện", "rỡ", "sợ", "ngạch", "ảnh",
            "nơ", "tiếc", "nghệu", "mạc", "bộp", "đập", "nhộng", "tun", "lẹn", "thư", "cần", "chiêu", "xào", "míp",
            "ộ", "giương", "chậm", "vừa", "đưng", "ắt", "chớp", "bút", "đèo", "luốc", "háy", "gói", "ới", "vật",
            "hốc", "lệ", "ram", "quanh", "sớ", "mãnh", "xơn", "phôm", "háng", "toả", "trò", "xảo", "hoc", "soạn",
            "thang", "chu", "bỉnh", "thúng", "sạt", "sưởi", "rổ", "kín", "giàn", "thưỡn", "rái", "nghẻo", "mẩm",
            "yêu", "phủ", "ngằn", "vừng", "phùn", "chạn", "cay", "khuy", "trốc", "nhành", "phường", "khơi", "nứa",
            "uổng", "vun", "trống", "nhấn", "thít", "ly", "ray", "rạn", "lỗ", "lút", "giỗ", "điu", "mung", "lây",
            "lẫn", "rợp", "ướp", "vở", "rịch", "ẹ", "mà", "lắng", "cõi", "đèm", "khuơ", "dắc", "nhão", "sún",
            "biếng", "vít", "đủi", "toái", "ngòn", "hoẹ", "bãi", "gàn", "dắt", "bệch", "rệu", "lình", "phớt",
            "phún", "náp", "tề", "nấp", "cup", "lặm", "thé", "dún", "kĩu", "kìn", "chèo", "thét", "tộc", "hụm",
            "ơi", "quăm", "nhũng", "ngẫm", "ngải", "bẩm", "ở", "đểu", "đâu", "sâm", "hênh", "nhì", "mầy", "quài",
            "dọi", "khoải", "dộc", "cậu", "gấy", "dán", "ụt", "bệ", "vờn", "hộc", "tối", "kiết", "phù", "bi", "oé",
            "thỉnh", "mắc", "thách", "xồm", "giầu", "sới", "vịm", "quều", "bứt", "mầu", "chữa", "kìm", "hến",
            "phum", "khép", "bội", "hẩy", "thừa", "dãi", "xắm", "diệt", "bốn", "nhăng", "mỵ", "nhiếp", "xoác",
            "khoèo", "lổm", "sít", "thuê", "hĩm", "nhẳng", "nhuệ", "biêng", "rẻ", "bước", "rơm", "bầy", "nhàng",
            "chửa", "dọ", "mám", "sắc", "vỗ", "măm", "bẵm", "lợ", "trừ", "ni", "tui", "bóng", "tiêng", "giũ",
            "thơi", "lãi", "quế", "phiệt", "gã", "ế", "tã", "nghẹt", "thô", "vụt", "dĩ", "vốn", "lưu", "liệm",
            "nhoà", "ngố", "đờn", "quạc", "sêu", "huê", "mái", "khem", "thồm", "dượt", "khánh", "nọ", "gằn",
            "oàng", "mèo", "tít", "lượt", "muông", "vựng", "chẻ", "sính", "kheo", "rông", "nhặng", "lóm", "noi",
            "dạm", "nhíu", "rỗi", "che", "luôn", "phi", "đẳng", "khang", "tư", "giun", "bạnh", "chàm", "lột",
            "chạnh", "giăng", "hầu", "bụng", "hoan", "lửa", "khỏng", "nhá", "ngửa", "chỏ", "giấm", "soạng",
            "khỉnh", "xen", "vày", "áng", "hẫu", "quện", "ỉa", "nặn", "xứng", "giặm", "sẻ", "nhương", "ngọ",
            "tuya", "trằn", "tiền", "tăng", "muỗm", "hoai", "gỏng", "tức", "mít", "thum", "ôm", "vẻ", "vịn", "chề",
            "thoã", "tơn", "oác", "hong", "cựa", "loàn", "hẩu", "xứ", "nhịn", "loảng", "phang", "thùm", "tý",
            "khắm", "é", "que", "hè", "rơ", "sám", "vẹn", "ợ", "xàng", "nọc", "chén", "chẳng", "quạt", "sô", "mủn",
            "phật", "bại", "đoảng", "xúc", "xoắn", "côn", "ngộ", "nội", "chua", "nghiệp", "xều", "vục", "mun",
            "đứng", "tứa", "tét", "rở", "sứa", "phảng", "kều", "tĩn", "bịt", "cợt", "giết", "ngóc", "trụt", "tuỷ",
            "trữ", "sìn", "nhoài", "đính", "trinh", "hỉ", "vẹo", "khắc", "nuy", "ốm", "bản", "sung", "sùm", "kiệt",
            "hiến", "chường", "mảy", "tính", "dưỡng", "rếch", "huýt", "nguẩy", "khen", "xuất", "gon", "nghía",
            "khênh", "phòi", "vọc", "nhúng", "chậu", "bềnh", "xỉnh", "kí", "ủng", "ghểnh", "ngày", "loà", "re",
            "ngon", "trợt", "hãy", "tè", "khao", "chờm", "chơ", "hưởng", "trớt", "rĩ", "tríu", "rặm", "lôm",
            "ngoạc", "tiếu", "ngươi", "trã", "óng", "ấn", "xửng", "toài", "trịa", "tiến", "hum", "chát", "chuẩn",
            "cời", "khỏi", "hoăng", "vê", "rò", "oách", "đụ", "cầm", "bịu", "lóng", "trằm", "chiện", "ri", "toẽ",
            "khạc", "sứ", "khứu", "nhảnh", "quẻ", "vổ", "tằn", "quạnh", "ìn", "tọc", "ngàng", "nhiên", "cặn",
            "hột", "tầm", "yếu", "choạng", "đổi", "bàu", "lõm", "vang", "nhun", "vớ", "quáy", "bẳm", "thoáng",
            "tan", "háu", "đèn", "diêu", "xệch", "thiêng", "cưỡi", "rày", "bây", "đũa", "tuyết", "nghệch", "quan",
            "sân", "cành", "thuỷ", "rơi", "đằng", "dòi", "ngứt", "tước", "xảy", "táp", "xỉu", "máo", "dũa", "nịu",
            "oang", "xộc", "trũng", "ghềnh", "sề", "chặt", "hê", "ngấu", "khác", "thụt", "váy", "chuồn", "kích",
            "sim", "ổ", "lửng", "kè", "nhỏm", "nhẻm", "nình", "còm", "trơ", "kịch", "thệ", "nò", "then", "lổn",
            "khuya", "vất", "ẩn", "nhậu", "nghểnh", "cau", "bách", "ngáy", "lở", "ních", "luỗng", "khô", "dường",
            "loả", "hệch", "chăm", "cộm", "lử", "phèng", "thè", "quýt", "sần", "sừng", "hời", "òng", "lã", "híp",
            "xốc", "rịm", "bá", "sũng", "bươi", "nhòn", "cửi", "ké", "lụm", "vé", "khoắn", "bíu", "ngồi", "phẳng",
            "tuệch", "xoẹ", "voọc", "láng", "phùng", "xái", "điều", "hiện", "hận", "sộ", "bứng", "không", "cọc",
            "phóng", "ngoai", "dó", "khập", "ngành", "trặc", "nhếch", "viền", "lính", "hẹp", "dụ", "chủn", "tách",
            "dốt", "cụi", "rườn", "giần", "hạnh", "thía", "rắn", "hàng", "ghèn", "uỵch", "chẽ", "gio", "nom",
            "boa", "khì", "thờ", "trùm", "học", "cẫng", "hứ", "khay", "thung", "vưởng", "ngân", "trao", "cắc",
            "hích", "cọng", "bẽo", "chĩa", "nghiến", "thi", "lạng", "cậy", "đoá", "siếc", "bặp", "cườm", "hăng",
            "cao", "nhùi", "ương", "ợi", "đù", "tìn", "trĩ", "khẩu", "gương", "tượng", "in", "thớt", "vại", "mỹ",
            "ngữ", "mắt", "khạch", "trồ", "hì", "hùa", "nón", "tải", "nây", "bỏm", "bẫm", "thín", "gai", "vào",
            "ồm", "quấn", "khuôn", "êu", "nỉ", "soóc", "giữ", "hững", "môn", "nệ", "rình", "giạng", "phũ", "cặc",
            "khả", "hẻm", "nhỡn", "nhoẹt", "đày", "lê", "gió", "nghể", "điếng", "trạc", "khải", "cớ", "vườn",
            "suối", "toá", "vọp", "lạo", "nọt", "loát", "thỏi", "giại", "hải", "xăm", "chúi", "bai", "nậm", "dịp",
            "vón", "quyển", "lao", "mề", "ráp", "thục", "nhoạng", "mền", "tật", "xược", "tuýt", "khè", "mác",
            "mạp", "mấu", "đọc", "choa", "cuộn", "ngùi", "toà", "bẩn", "bạch", "chớt", "xập", "rưởi", "trâu",
            "mụn", "sam", "nhạc", "uý", "bàn", "thẩy", "cuốc", "múp", "mảnh", "hay", "sóng", "nộn", "tuổi", "lặt",
            "sèo", "vùn", "ruốc", "sụp", "diêm", "thêu", "ninh", "doi", "bợn", "xõng", "đĩ", "gấm", "bừa", "thếch",
            "dện", "nghị", "gi", "trộ", "nớt", "cước", "rạng", "dè", "lủm", "váp", "rế", "chum", "giỏng", "quớ",
            "vượn", "dím", "sục", "chài", "cháy", "nhội", "mũm", "ấp", "sẵn", "đằm", "ngàn", "choé", "quạu", "lật",
            "khít", "rùng", "lão", "hên", "rặng", "đờm", "khoái", "lo", "trấu", "bặn", "nghiên", "phở", "việt",
            "váo", "tửng", "chuông", "nếp", "sánh", "đe", "ngoãn", "bớ", "nu", "coọc", "bửng", "còn", "manh",
            "xóp", "túa", "nhở", "ảo", "rèn", "rậm", "tại", "chặng", "khăng", "hoằn", "xúm", "khoẻo", "oằn",
            "chào", "meo", "rủn", "chỏng", "vui", "mía", "kháy", "thiệt", "báo", "dỏm", "quật", "uỷ", "rúm",
            "soái", "nhẻ", "hũ", "gợt", "cắm", "khó", "hoạt", "nuột", "ngoạy", "chọc", "hãm", "khau", "cục", "chữ",
            "lẻo", "dám", "tuệ", "bấn", "lạc", "chan", "ghẹo", "lỗi", "dằm", "húm", "tra", "lũn", "phắt", "mớm",
            "phưỡn", "ất", "tá", "luồng", "đề", "lơ", "chãi", "áy", "ịch", "nùi", "vòi", "ẻo", "sắng", "đô", "ả",
            "chầm", "dàm", "vựa", "đẹt", "thào", "tùng", "rủ", "dở", "ngắt", "gác", "xay", "lị", "tài", "nhướng",
            "hây", "lờ", "gan", "mòn", "mô", "nghé", "dự", "điệp", "lũ", "nẫu", "choài", "mếch", "bồ", "díu",
            "long", "liếng", "rệt", "bẻo", "khuỵ", "gạc", "khoản", "nhẩn", "gượm", "ranh", "róc", "đăm", "bợp",
            "xoáy", "phỉnh", "sây", "tọt", "đoạ", "đật", "nhấc", "lên", "nền", "nua", "hán", "bẳn", "riềng", "gồ",
            "phế", "vạnh", "nỗi", "đưỡn", "trạng", "tự", "sạp", "buồm", "tháo", "nhắt", "thõng", "mách", "dạ",
            "rằm", "bải", "giập", "độn", "vẫn", "dạo", "dận", "gợn", "sau", "ngứ", "mèng", "ten", "huyễn", "khỉ",
            "sấu", "minh", "ức", "cốc", "phì", "dẩn", "giới", "trù", "lừ", "lưa", "xuyết", "co", "ối", "quàu",
            "trên", "đẹn", "bò", "toe", "sồng", "khoa", "từng", "cũi", "trục", "nhăm", "lanh", "đứt", "chởm",
            "tưng", "gỏi", "rỉa", "vờ", "chương", "lặn", "rẹt", "buộc", "nôi", "gà", "viễn", "găm", "dải", "gụi",
            "nhoi", "xốn", "nhàn", "mất", "bèn", "tuyn", "kháp", "tổn", "số", "những", "sịp", "tròi", "mực", "dệ",
            "nhọ", "gùi", "trõm", "chợn", "quyền", "lủi", "nở", "duối", "thằn", "chục", "choai", "bổn", "bõng",
            "khoeo", "giếng", "chễm", "dột", "cẫn", "sầu", "nả", "móng", "thẫm", "chùng", "khá", "bọc", "khung",
            "xách", "hồn", "kền", "ném", "vách", "nớ", "ban", "trọng", "nhẫn", "lọm", "tảo", "vập", "giấc", "tạm",
            "đầu", "giê", "vảy", "trào", "lựa", "tíu", "rúng", "lề", "rầu", "ngốn", "bơi", "đúng", "khắp", "thện",
            "chím", "hiu", "chững", "lẹt", "rừng", "nhịp", "nốc", "của", "ngoẻn", "phạt", "thấy", "khùng", "vững",
            "choá", "giẫm", "tầu", "lòng", "ửng", "lóc", "thời", "thoá", "tịt", "trồi", "miến", "sái", "trành",
            "phăm", "sữa", "lồm", "gạt", "chới", "đếm", "khù", "đuồn", "thườn", "gu", "hoà", "bồng", "chồi",
            "loét", "mầm", "vú", "xiên", "liếp", "mạn", "mui", "cộc", "muôn", "tình", "rôn", "chưởng", "dề",
            "ngoạm", "nan", "be", "dội", "càng", "thũng", "lọc", "lá", "dẫm", "chó", "bõm", "ló", "na", "rùm",
            "pháo", "rít", "mọi", "rờ", "gượng", "nghiệm", "chệch", "xiềng", "thỗn", "hanh", "chăng", "xên",
            "lạch", "trói", "tháu", "thăng", "chái", "li", "beo", "nhú", "lựng", "giỡn", "quỵp", "cháng", "nhánh",
            "giông", "nhanh", "mên", "mọp", "nhậm", "mơn", "chẽn", "bắng", "đảnh", "sơm", "trại", "yểu", "trẩu",
            "khân", "nhuếnh", "phái", "go", "ọ", "lạt", "ồng", "quá", "ắc", "khỏ", "kình", "lòn", "vống", "mừng",
            "xoá", "phổ", "cối", "vốc", "goòng", "đêm", "chong", "thao", "thưa", "thược", "óp", "kiếm", "ạt",
            "nhẽo", "võ", "lớ", "rách", "leng", "dồi", "vữa", "nhởn", "phối", "gắng", "rức", "loé", "rốc", "dả",
            "phen", "oa", "nhẳn", "bịnh", "sệt", "cợp", "ghét", "cũn", "xíu", "khấn", "bừng", "quyết", "rụp",
            "yến", "rai", "gào", "cuốn", "nậy", "hỗn", "nhứt", "cot", "uống", "rập", "đọn", "beng", "kèn", "nhướn",
            "lia", "kỳ", "tim", "hẩng", "tri", "khiếu", "lảng", "ngạnh", "khụng", "khề", "chấu", "chủ", "ui",
            "phê", "vầng", "rầm", "cọn", "khoáy", "nhố", "soa", "ổn", "lơi", "quánh", "ghì", "vị", "thẫn", "day",
            "lún", "bảnh", "vãnh", "đúp", "nhớm", "rãi", "la", "nẫng", "bán", "nhơn", "sống", "giở", "xĩnh",
            "quắm", "dõng", "ngô", "chọp", "gặm", "cơ", "chiêng", "lể", "xoẳn", "nghếch", "vạng", "trát", "chơn",
            "kiệm", "tiêm", "phách", "dói", "vén", "tướp", "nhằm", "ngờ", "cheo", "chành", "hóp", "trận", "tụi",
            "cạp", "vậy", "ưa", "ngấm", "phung", "cắt", "miếng", "xoét", "nhoè", "cùi", "giạt", "tên", "thú",
            "trỉa", "chão", "nõn", "xoài", "luận", "hấm", "thia", "ha", "mình", "tụm", "ken", "nưa", "nô", "phẩy",
            "se", "tụ", "lắm", "kèm", "trướng", "vác", "phốc", "sẻn", "phích", "dào", "túng", "iu", "lới", "nhón",
            "thỏ", "rặn", "khu", "hảng", "đệ", "nhau", "lổng", "giếm", "tin", "ghim", "mão", "đồn", "ngả", "tua",
            "nuộc", "tru", "vỡ", "độc", "mài", "nể", "trúm", "động", "bốc", "đem", "xôi", "săm", "nhãn", "giỏi",
            "suỵt", "tơ", "dứ", "rứa", "rấn", "phơi", "tái", "đeo", "mượn", "ngắm", "chếnh", "tởn", "sộp", "xịt",
            "hự", "chuyền", "trăm", "trạnh", "nhẵn", "trừu", "khoanh", "tuy", "loài", "trăng", "cữu", "xưa",
            "thốt", "ché", "nhách", "ố", "sanh", "hý", "níu", "ngọn", "khoán", "ụp", "sến", "rị", "thoa", "mươi",
            "phạm", "đỏng", "triệt", "mươn", "chéo", "lẹ", "tương", "thầy", "xềnh", "xộn", "diệp", "dùng", "xệ",
            "dí", "ngớn", "quýnh", "xén", "dộp", "cuồn", "rọc", "xoàng", "vẳng", "bộn", "dấy", "vẩu", "tục",
            "giữa", "tôm", "hại", "chích", "dừng", "phới", "ngoằng", "dù", "rân", "ben", "chúa", "khước", "đều",
            "kẹt", "mốc", "vô", "bịp", "mế", "phĩnh", "khôn", "loá", "bếp", "bôn", "trối", "trập", "hửng", "chở",
            "trơi", "bit", "quào", "cồng", "phỏng", "đỡ", "thảm", "rè", "tín", "to", "nơm", "lấm", "thoái", "ngủ",
            "khọt", "ghe", "giàu", "tom", "xoèn", "trỗi", "ngoé", "trọn", "úng", "ra", "truông", "xính", "ít",
            "nhổm", "múi", "lim", "mại", "mồ", "xớt", "xục", "phiên", "tặn", "khẳm", "ảng", "bỉm", "sỡ", "ngậy",
            "dĩn", "thán", "ốt", "nhai", "nhít", "húng", "vênh", "dờn", "gôn", "đấu", "loen", "hén", "tô", "ngật",
            "há", "hương", "tóc", "phả", "trương", "đớn", "xúp", "mênh", "chỉnh", "voan", "mằn", "xát", "uỳnh",
            "nhum", "gùn", "huấn", "khoe", "sõng", "hám", "cóng", "ạch", "thính", "đần", "xuân", "đo", "gờn",
            "cộp", "tuốc", "bạc", "phần", "để", "súng", "nì", "đủ", "thắc", "tém", "trồng", "ề", "chợp", "tích",
            "trội", "lụt", "tươi", "xoong", "cuội", "nhạt", "xẻo", "biến", "rồ", "nghịch", "tói", "nhe", "đỗi",
            "chóng", "găng", "gột", "phướn", "líp", "ro", "trau", "nghén", "vó", "giao", "giổi", "quý", "cúm",
            "dam", "nhám", "gốm", "rào", "sương", "keo", "thịnh", "đoài", "luân", "phừng", "bung", "ung", "từ",
            "bí", "rang", "trợn", "giai", "đè", "noãn", "guốc", "thò", "ứ", "lỏi", "miêu", "khừ", "ẳng", "tằm",
            "run", "ẩm", "lệch", "trìu", "hin", "trắm", "lẻm", "xừ", "tặng", "cạnh", "tánh", "lum", "nhể", "rảy",
            "gạo", "nhuộm", "rí", "chác", "đom", "bất", "sất", "nhuần", "gặc", "ràng", "lìa", "rống", "chôm",
            "soàn", "kha", "lỏn", "mẹt", "sỏ", "hoài", "phếch", "kẹo", "dưng", "sụt", "giàng", "ập", "hác", "muội",
            "thổi", "chọt", "bù", "vơi", "nên", "đáu", "nhảu", "chìa", "nẹp", "ngúc", "nạy", "bợ", "bỉu", "rồi",
            "quầng", "liên", "mẩu", "tấp", "gọi", "nhừa", "ởn", "phẹt", "loàng", "nhoẻn", "múa", "dút", "nịnh",
            "cuống", "khoằm", "tấm", "tỉa", "rỉ", "nhà", "cáp", "khâm", "dãn", "nòng", "sàm", "xỏ", "kiểu", "phét",
            "rài", "đơn", "mả", "nhân", "nghỉ", "hòn", "cả", "xói", "giầy", "thột", "rỉnh", "trút", "trích",
            "cheng", "chượp", "trăn", "đét", "nằng", "giốt", "so", "tể", "nhõm", "bủng", "trụa", "bố", "tèm",
            "nâu", "tỉnh", "phồng", "ổng", "giờ", "khảo", "áo", "cong", "sứt", "nghìn", "phèn", "hoắc", "buổi",
            "rộc", "rén", "biểu", "kỉnh", "mang", "lìu", "trưa", "viếng", "mửa", "mèn", "bươn", "nải", "nỡ", "đáp",
            "dựng", "lủng", "vãi", "niệm", "vùi", "sắm", "líu", "cháu", "diềm", "tỳ", "chỏi", "thâm", "toáng",
            "mòng", "khèn", "lệt", "hùi", "xọ", "lấc", "may", "tăm", "mi", "riếu", "nhay", "trùn", "đận", "bẵng",
            "suất", "đoạt", "lịa", "xiêu", "bụa", "mót", "kiểng", "xá", "thắn", "gấu", "đồng", "dúi", "bênh",
            "nói", "mọn", "đong", "trải", "lẽn", "phẫu", "tuyển", "chán", "ngầy", "thòng", "điềm", "lẩn", "lấp",
            "đung", "sị", "sẽ", "bọ", "sạn", "đối", "dương", "tranh", "thượng", "vù", "hạt", "khan", "băn", "bọn",
            "nụ", "gốc", "xu", "ùng", "tuấn", "ngoéo", "ngớ", "tênh", "tẽn", "lướng", "thai", "đôm", "mởn", "hip",
            "phiêu", "lân", "lẩm", "tiễn", "nguôi", "xịu", "giềng", "thặng", "sực", "cụp", "hổng", "gì", "trưng",
            "nảy", "ĩ", "dừ", "len", "nhiếc", "huých", "nam", "gẩm", "rắt", "hòm", "đái", "mĩ", "lởm", "nộp",
            "xường", "cọ", "ngầm", "lém", "ngôn", "lúc", "thiu", "cạc", "gỉ", "cưu", "thuẫn", "trà", "nơi", "khoả",
            "tạng", "mánh", "thị", "gởi", "luỹ", "tông", "ngùn", "kít", "rúc", "sầm", "cột", "mâm", "lau", "rá",
            "nãy", "tồi", "phạn", "nhíp", "thuyền", "vỉ", "kếu", "mộng", "xệp", "ngâu", "mẫm", "muộn", "sạc",
            "quác", "tẻ", "phay", "hinh", "gian", "nhốc", "chợt", "dáng", "thuận", "mứa", "trũi", "cho", "khê",
            "đùn", "nhớt", "đen", "khiên", "bền", "thụi", "lộp", "dụm", "rủa", "nghi", "vẽ", "trèm", "vành",
            "chét", "vát", "hiểu", "tỏ", "đềm", "bụ", "nhường", "giá", "thì", "bồi", "tinh", "đay", "phấp", "bón",
            "ngũ", "nước", "xìu", "hốt", "lướt", "buốt", "don", "mờ", "mưa", "tị", "tráo", "nượp", "nót", "cuộc",
            "dối", "nhụ", "dần", "vạn", "quỷnh", "thóm", "nặc", "bo", "kia", "ốc", "nùn", "núng", "lâu", "bé",
            "nhục", "thố", "chước", "võng", "hoẻn", "chanh", "trệt", "nờm", "rượt", "sướt", "nghèn", "khoác", "bờ",
            "ao", "chúc", "mùi", "nghịu", "dém", "xủng", "thu", "trắt", "kênh", "sệ", "sang", "ren", "chiền",
            "lểu", "nồng", "gảnh", "soong", "sẩy", "nới", "chốt", "nhắp", "toạ", "lòi", "nhoang", "ựa", "ghẹ",
            "sóc", "trúng", "rường", "lấy", "đuổi", "giạ", "sủa", "châu", "sẹ", "hom", "rù", "quệt", "nỗng",
            "nhầy", "y", "cạ", "bó", "lớt", "giật", "phao", "đợ", "ưng", "toa", "bùn", "thăm", "xịch", "vã", "ke",
            "đôn", "gãy", "mỉ", "ti", "lẫm", "cản", "bẹp", "têu", "thà", "bộng", "dằng", "tro", "rỡn", "si",
            "ngổm", "râm", "dá", "rao", "dẽ", "loẹt", "gửi", "cẳng", "đễnh", "đai", "đít", "xúi", "tổ", "liêm",
            "dơi", "khuýp", "buông", "tanh", "gắn", "triển", "tĩu", "chắp", "mạ", "cội", "tuộc", "guộn", "khiêu",
            "gừ", "tõm", "khạp", "xàm", "rộp", "đẵng", "sành", "nhịt", "kiệu", "bựa", "mét", "dom", "đảo", "nại",
            "tuý", "phố", "bặt", "lúm", "mương", "bần", "rớm", "hỏng", "hụ", "vịt", "chấm", "kỷ", "hao", "hàu",
            "nó", "dộng", "lõng", "toạc", "phổi", "quở", "đông", "phòng", "ngóp", "quỳnh", "mã", "mìn", "tà",
            "gập", "chõng", "lành", "xấp", "lương", "công", "rợi", "nong", "dền", "ớ", "gổ", "lỵ", "thẩn", "đình",
            "khẩy", "lịnh", "ru", "phắn", "thêm", "ríu", "lỏm", "nanh", "nhệch", "lắc", "tửu", "đa", "thắt",
            "nhạnh", "điếu", "ghê", "nhốt", "lựu", "nhác", "mơi", "bã", "trưởng", "dìm", "lú", "chòi", "sặc",
            "vịnh", "đé", "cỏi", "tống", "sơn", "húp", "sếu", "khố", "dế", "sụa", "bát", "thỉ", "viển", "khán",
            "hướm", "phất", "nhũn", "đạp", "chẹn", "ngỗ", "khạng", "sặt", "quê", "kỵ", "chí", "cụng", "lẫy",
            "khám", "sôn", "hoàn", "nịt", "nựng", "nhoàng", "nguyên", "chảy", "bứ", "vân", "đức", "đi", "cung",
            "kẻ", "định", "dóc", "ỏi", "háp", "lẻ", "tràm", "ngoắc", "nhoam", "rả", "dợn", "giọi", "sấp", "dặn",
            "trễ", "xuổng", "tì", "ích", "nuối", "thất", "nghỉm", "rụng", "hoắt", "khấc", "vanh", "lẹo", "mận",
            "ngưu", "giống", "trạt", "ôi", "dị", "bơ", "vỉa", "thảnh", "xèo", "đạn", "vè", "thí", "lãm", "cóm",
            "tềnh", "khiêm", "cõng", "dọng", "mảng", "khoáng", "giẫy", "khiu", "hạ", "tiềm", "sẹo", "nêm", "sồi",
            "chang", "chườm", "xắn", "mọng", "gỡ", "phui", "vòng", "nhoen", "toè", "rét", "ve", "phom", "hễ",
            "dàu", "trâng", "khươn", "tiện", "khơ", "sụ", "bùng", "bạu", "lục", "gộ", "thốn", "ngặt", "giải",
            "náo", "guột", "tây", "trổ", "nhựa", "thèn", "đại", "cào", "nộ", "bợm", "tàm", "réo", "xoẹt", "câng",
            "háo", "duyên", "xi", "khía", "trề", "phình", "ngẩm", "quèn", "muồi", "thơn", "rỗng", "hố", "rổn",
            "sền", "bỉ", "gồi", "săng", "xón", "quây", "phận", "bảng", "tẹt", "nhớ", "choèn", "xạc", "phốp",
            "dang", "lưới", "hớp", "rệ", "rê", "hắn", "dược", "nằm", "rẩm", "nhợt", "mường", "ốp", "khần", "hõm",
            "quại", "ho", "son", "rún", "thấp", "cử", "tê", "lướp", "nang", "treo", "am", "nghễ", "khằn", "mồm",
            "bịa", "củng", "dĩa", "kỉ", "bướng", "hoãn", "nhấp", "trộm", "rửa", "nem", "xô", "cặm", "chuỗi", "chê",
            "chợ", "trảy", "rói", "nhịu", "cứng", "vậm", "đoác", "ngoại", "mích", "trạo", "lếu", "sẫm", "ngưa",
            "quáng", "lũng", "thợ", "nghềnh", "gở", "vướng", "sọt", "tẩu", "giày", "pho", "trọ", "bìa", "nghễnh",
            "tuột", "sác", "vọi", "gẫm", "chuyên", "đang", "xó", "sợi", "ọp", "găn", "đực", "xở", "lúi", "loằng",
            "dà", "mặc", "ứng", "choi", "xử", "vồn", "bong", "rìu", "vuông", "cũng", "ấm", "típ", "thoải", "lỉu",
            "trui", "xâm", "doạng", "hĩ", "miễu", "mạy", "chớ", "õng", "duệ", "triềng", "tròm", "khoang", "lêu",
            "tếch", "thê", "nguậy", "cụ", "khuẩn", "mát", "giả", "nạm", "dác", "nhấm", "ủi", "niêu", "lượn", "trở",
            "ngõ", "mễ", "rực", "tuyên", "thoắt", "vĩnh", "xị", "cầy", "lọng", "sôi", "ký", "trí", "chất", "nẹ",
            "toòng", "phệ", "vẫy", "phô", "đứ", "cân", "chày", "toanh", "áp", "xem", "nhoá", "trọi", "xác", "qua",
            "cỗ", "liễu", "ngợm", "bà", "tăn", "quả", "xẹp", "dáy", "heo", "vẻo", "rớt", "tập", "xình", "xỉa",
            "luý", "xong", "ỉm", "bực", "vu", "đẫn", "than", "khắn", "gặp", "ca", "nhớn", "hu", "tem", "ép", "đợi",
            "dùa", "mùa", "róm", "ngoái", "huỵch", "chuồi", "mốt", "kiềm", "hoải", "tòng", "gấc", "dóng", "xưng",
            "huyệt", "rộng", "thày", "nhé", "chược", "ồ", "sĩ", "bỏng", "dẹt", "giễu", "đoạn", "voi", "khọm",
            "giây", "nã", "lởn", "chứng", "rạp", "hộp", "bướm", "úp", "liền", "biếc", "rất", "mồi", "độ", "mẩn",
            "đọi", "lè", "săn", "châm", "tỏng", "mùng", "chậc", "chớm", "tâm", "cống", "đàng", "giặt", "dịt",
            "điển", "eng", "hop", "rôm", "chả", "trước", "hớn", "lậu", "táy", "nghề", "trêu", "lẹp", "kiều", "gân",
            "phụt", "sùng", "phên", "khuyết", "tiết", "tuần", "quãng", "suyển", "trúc", "gáo", "thúc", "mẹ", "tó",
            "cứt", "ngoặt", "thưỡi", "làng", "trụng", "ưu", "hão", "trang", "khẳng", "ngắn", "chút", "niệu", "đóm",
            "hai", "ôn", "chênh", "rác", "phứt", "tậu", "mua", "đến", "đẽo", "non", "triện", "mải", "giảo", "rèm",
            "thụng", "giền", "chõ", "móm", "đương", "qué", "gọng", "chêm", "lĩnh", "reo", "hẻn", "xây", "bỗng",
            "vợi", "loe", "choẹt", "nhoáng", "múm", "dời", "dầy", "xọc", "dung", "cọm", "đột", "sườn", "ín", "nào",
            "buồn", "câm", "chấp", "rồng", "sòi", "bống", "hoạch", "uất", "bậc", "bìu", "hềnh", "ù", "vóc", "khin",
            "um", "dũng", "kề", "rẩy", "dẩu", "thớm", "phí", "nẩy", "ư", "cáu", "bạt", "xiểm", "triêng", "nhặm",
            "mần", "trực", "sể", "hặc", "hỏi", "bệnh", "xuềnh", "phà", "cài", "oà", "tấc", "quà", "tưa", "hư",
            "hươm", "thuốc", "câu", "tung", "mướp", "thạo", "nhèm", "cạn", "sút", "oạch", "toẹt", "mủm", "đồi",
            "nia", "dụi", "và", "tràng", "huy", "sùi", "trá", "chừng", "sàn", "nách", "xông", "hoắm", "quặng",
            "báng", "lữa", "nấc", "khi", "vấp", "lí", "hừm", "dẫn", "nhỉnh", "trẻ", "mâu", "rể", "tráp", "muỗng",
            "ngoàm", "rạt", "eo", "ỉn", "nhượng", "nhọn", "kẻng", "tràn", "ngói", "sụn", "thủ", "gióng", "mềm",
            "riết", "tau", "ngợp", "quyến", "nôn", "vói", "trân", "mẩy", "lặp", "vối", "dăng", "rộm", "nổi",
            "doãng", "chia", "phiếu", "mom", "bài", "vùng", "phị", "uột", "hàn", "hít", "vùa", "bấu", "phiếm",
            "ngưỡng", "loăn", "quặt", "vế", "dàng", "khào", "nhậy", "húi", "vện", "nhằng", "kháu", "quảng", "tồn",
            "giỏ", "diễu", "chip", "cựu", "rơn", "nẻo", "nặng", "ta", "nứt", "loắt", "gưỡng", "rap", "phinh",
            "trôn", "toán", "vam", "nĩa", "cưỡng", "băng", "cồm", "luỵ", "lẹm", "nghền", "gié", "phộng", "nhu",
            "ngủn", "bươu", "giấu", "thài", "thủng", "điệu", "phiền", "ngắc", "phớn", "dỡ", "sổng", "tạnh",
            "tuyệt", "sỹ", "de", "xéo", "nhuốm", "kiếng", "rem", "hớ", "mỡ", "nhị", "ẽo", "đặt", "mò", "toác",
            "hành", "rỏ", "bộ", "vức", "phác", "ngạt", "xoa", "đoán", "kiếp", "nghển", "rợ", "gành", "truyền",
            "choè", "xì", "sinh", "hãi", "xía", "tảng", "tườu", "diều", "láu", "veo", "nhôi", "mịch", "cặt", "lặc",
            "rùn", "thiết", "nhạp", "cư", "thuỳ", "đụn", "bít", "kể", "gay", "bổ", "siu", "quẫy", "ã", "hó", "bới",
            "nhúa", "trượt", "tễ", "quằn", "bắc", "mau", "lô", "loi", "rốn", "phập", "nhỏ", "lác", "ngụm", "sướng",
            "xao", "miệng", "chừ", "hạch", "lượng", "đêu", "khứa", "mây", "doãi", "chép", "ngừa", "xét", "dưa",
            "lồng", "vầy", "khoẻ", "điểm", "phìu", "trĩu", "hỏn", "thói", "bẹo", "thát", "kẽo", "cùn", "ghếch",
            "tìm", "chửi", "diết", "hồng", "giói", "góc", "tẹo", "còi", "rát", "vên", "trèo", "teng", "xầu",
            "hùng", "yếm", "cụt", "rẫy", "hơ", "hoắng", "chức", "loè", "miên", "loai", "kiến", "gọn", "quăng",
            "giảng", "thểu", "lánh", "khắng", "gậy", "nhập", "mến", "tiều", "chiếc", "nề", "oẻ", "ngơ", "cón",
            "vết", "khí", "xin", "nuốt", "thay", "phán", "rứt", "thọ", "pháp", "đứa", "đố", "cứu", "vây", "chi",
            "vạm", "hem", "trợ", "xơ", "chính", "cơm", "bự", "thứ", "gằm", "chũm", "dựa", "lát", "khuất", "mè",
            "sáng", "tán", "nườm", "dẻo", "rước", "thướt", "chạt", "cấm", "phàm", "chuệch", "ngồn", "hiển",
            "trảng", "thắng", "kiểm", "đùa", "nần", "thép", "ngụa", "đền", "đốn", "thoại", "dữ", "ổi", "gừng",
            "mủ", "ran", "rong", "nhín", "ghế", "lởi", "càu", "đúa", "trặn", "mứt", "ẩy", "lẵng", "bị", "liềm",
            "ngoẵng", "no", "lạnh", "lứa", "nhẩy", "nhem", "xuê", "mút", "đềnh", "sủi", "đúc", "ếch", "nòi", "món",
            "quạch", "phễu", "giỏn", "oái", "bô", "lất", "thua", "luốt", "khiếp", "tỵ", "vôn", "rặc", "lụ",
            "choảng", "lốt", "cấp", "đổ", "khiễng", "thánh", "thoạt", "khúng", "láy", "ngoèo", "đin", "ngai",
            "trệu", "bằn", "bua", "rung", "nhã", "vạt", "lưng", "mơ", "sựng", "va", "sãi", "xoảng", "quéo", "gắm",
            "tằng", "nhiễu", "ki", "hợi", "thuộm", "làm", "oai", "nghệ", "toáy", "ngõng", "dép", "quất", "vải",
            "thèo", "vãn", "cốn", "huống", "trụi", "choác", "rạy", "xối", "trần", "lầy", "thìu", "tuất", "tuỵ",
            "vóng", "hừ", "lỉm", "tủm", "bang", "khàng", "riu", "hạng", "diên", "tiêu", "thịch", "mậu", "siểm",
            "trầy", "nõ", "hoen", "chệ", "củ", "ghiền", "phơ", "rười", "óc", "truyện", "giục", "nghĩnh", "rươn",
            "chặp", "bớt", "mếu", "nhải", "bão", "gàu", "xuẩn", "tẩn", "quýu", "thơ", "hĩnh", "địa", "lợi", "trơn",
            "dụng", "chạc", "rắm", "vinh", "vót", "răm", "rối", "kiếu", "gạch", "phào", "khoắt", "oẳng", "trủ",
            "què", "cơi", "bạo", "sửu", "lộm", "ngư", "đẫm", "lang", "lép", "nhoèn", "cộ", "tai", "nôm", "hậu",
            "trầm", "mọc", "phè", "xiếc", "lầu", "vàng", "điệm", "sồn", "vằm", "nhụt", "nhạy", "quán", "cương",
            "ỏm", "đuôi", "bều", "hoảng", "tu", "luýnh", "búi", "nhận", "giấn", "hói", "rám", "đất", "tàu", "lịch",
            "khum", "bơn", "cẩm", "vằn", "cớn", "sòn", "cô", "niềng", "trẻo", "sáp", "mười", "hở", "nhối", "cằn",
            "hét", "ngẳng", "gật", "cuối", "lăm", "khống", "cường", "bương", "gang", "sói", "phầm", "ngập", "soi",
            "mé", "luy", "chiên", "khiêng", "bựng", "trết", "cớm", "chiều", "kêu", "lúng", "quỵ", "mủng", "phỗng",
            "dõi", "mẹp", "phệt", "lốc", "xè", "tum", "vọ", "nghè", "liếc", "lơn", "ngộn", "miết", "nấy", "gội",
            "rìa", "ngơi", "bỏi", "phát", "bức", "vũ", "trệch", "oe", "nhớp", "quẳng", "ngùng", "chúm", "nóng",
            "rây", "rỗ", "chảo", "chũi", "chằn", "cấc", "sồ", "giâm", "vổng", "ngâm", "lùn", "phảy", "huyên",
            "bẩu", "chít", "chằm", "oải", "vểnh", "kiêng", "hoe", "cảm", "chuội", "trong", "né", "sê", "suồng",
            "lùng", "dượng", "lay", "tết", "xẹt", "đỏ", "nhợ", "xùng", "mỉm", "gườm", "sớt", "nhờ", "nạn", "hâm",
            "kéo", "nghệt", "lệnh", "đợt", "quén", "cùm", "xẻ", "lạp", "vảng", "khặc", "mỉa", "khẩn", "hú", "lỏng",
            "hạm", "lùm", "quen", "cạch", "ịt", "giường", "giậm", "thuế", "cánh", "tẩm", "chiếp", "gút", "sượt",
            "bằng", "quang", "ngòi", "lụa", "gạn", "căm", "ngưởng", "mấy", "tang", "nỗ", "siêu", "dô", "dàn",
            "lều", "chuôi", "ỏng", "canh", "quày", "bọt", "bầm", "nhông", "nầm", "hách", "ma", "quầy", "bắt", "rễ",
            "víu", "xẻng", "nhần", "chách", "ráng", "mặn", "giú", "tạo", "nép", "mỏng", "suyễn", "táng", "mết",
            "hiềm", "oặt", "lãng", "hoét", "quờ", "nghẹn", "rải", "trâm", "chíp", "hệt", "nư", "khuỷu", "dập",
            "náu", "đỉnh", "ghẽ", "phức", "ngoe", "quốc", "hon", "đuểnh", "phin", "xú", "thui", "ráy", "dậm",
            "sản", "chỉ", "khờ", "nhuyễn", "xoả", "chầy", "đặn", "dờ", "đẹp", "hết", "nhảm", "gàng", "vích",
            "quắp", "bói", "thập", "khui", "ác", "cứa", "bê", "hển", "múc", "nhật", "tâu", "súp", "ươi", "nút",
            "rẫm", "dóm", "huệ", "dặc", "hái", "khâu", "cất", "đẫy", "ròi", "chỏm", "thước", "nhoàm", "thạch",
            "quải", "mộ", "nhè", "nháp", "nhung", "bể", "phơn", "sênh", "phàn", "thớ", "ghi", "đục", "chen",
            "trọc", "sét", "è", "quấy", "loã", "tày", "sáo", "khởm", "chốc", "nhủ", "ngón", "trịt", "cuỗm", "sâu",
            "tiếp", "hấu", "mãng", "thiện", "xước", "kế", "khẹt", "sảo", "phồn", "xịn", "chàng", "tễnh", "xậu",
            "ngão", "tháp", "lãn", "ngổn", "phựa", "cửa", "lớn", "đế", "mức", "chặc", "chơm", "khòng", "diếp",
            "dưới", "dính", "xấu", "rệp", "hối", "lai", "ực", "tuồn", "tồ", "thầu", "nghét", "dát", "ải", "nhéo",
            "nguệch", "hắc", "hiền", "mo", "cam", "khuếch", "bốt", "dinh", "quậy", "cưa", "nhuận", "cặp", "banh",
            "dèn", "chinh", "bộc", "ngò", "nhôm", "vời", "xạch", "pha", "khượt", "đò", "bục", "oát", "rợn",
            "khuỷnh", "đùi", "bụm", "nê", "đậm", "nhắng", "nhự", "hiệp", "gãi", "trai", "cu", "quết", "đả", "thếp",
            "khuỵu", "phôi", "lăng", "xảm", "hiên", "xèn", "phổng", "phịa", "kiêu", "bết", "dé", "tránh", "ngồng",
            "kìa", "xam", "me", "kẹ", "đu", "nhó", "bến", "ơ", "gông", "nhễ", "vươn", "ngớt", "đõ", "thuỗn",
            "viên", "kếch", "gươm", "túc", "dứt", "nấng", "hoạnh", "khuân", "đua", "lẩy", "biện", "đớ", "nét",
            "nện", "đá", "dặng", "bậu", "rì", "giắt", "hẵng", "xoành", "ngán", "chuối", "đát", "đạm", "đú", "hổ",
            "mum", "nhây", "tuỳ", "nhẹp", "truất", "ràn", "bưởi", "hờm", "hỏ", "côi", "sập", "kị", "xưởng", "tầng",
            "rão", "lói", "trắng", "tời", "ệch", "cám", "nác", "đanh", "phong", "chội", "te", "liếm", "chiểu",
            "náng", "trịch", "cốm", "chì", "khoảng", "xởi", "thâu", "dim", "sảy", "luồn", "át", "niu", "hoi",
            "xeo", "lảnh", "điếc", "hỷ", "ướm", "nghểu", "sổi", "ngừng", "đau", "đăng", "duỗi", "cẩu", "rưỡi",
            "phép", "xống", "hợm", "tiệc", "huỳnh", "chồng", "phỉ", "xỉ", "xụp", "ầu", "vạch", "ngốt", "ếm", "ào",
            "sen", "nạo", "thầm", "khấm", "lằng", "hằng", "ngao", "khoắng", "thửa", "kì", "mãi", "nít", "tép",
            "trật", "đệm", "lừng", "bíp", "lán", "xáp", "mạt", "đầm", "phuy", "chuốt", "hể", "giẻ", "ngửng",
            "nghẹo", "thềm", "dệt", "ngước", "rươi", "nghe", "nghiệt", "giấy", "sọm", "cẩn", "chiếng", "thuyết",
            "trớ", "nén", "rót", "gáp", "rón", "chiếu", "nọng", "sẩm", "sớn", "lỡ", "tay", "lằm", "hường", "đượm",
            "sượng", "tia", "ngảnh", "hẳn", "phản", "trô", "bậy", "sà", "loay", "giãn", "vền", "suýt", "em", "mõ",
            "hữ", "lọp", "rủi", "sởn", "huơ", "giang", "thìa", "lờn", "tơi", "dành", "xoi", "niên", "khử", "đốt",
            "cật", "cởi", "núi", "lèn", "bành", "huếch", "vũng", "lúa", "keng", "cách", "thưởng", "nuốm", "trụm",
            "trổng", "đạc", "tướng", "lận", "thiếc", "tột", "hợp", "hoành", "nhóng", "sào", "điên", "buồng",
            "quăn", "xực", "hập", "nẫn", "nghỉu", "thẳm", "gảy", "hưu", "khảm", "deo", "loong", "ngào", "cùng",
            "thuổng", "măng", "bú", "nhỡ", "giằm", "lúp", "thới", "trôi", "mưỡu", "cảo", "hi", "duộc", "mẻ",
            "thiêm", "đốc", "củm", "hậm", "vấy", "rớ", "nay", "rựng", "lốm", "ngây", "sọc", "tốp", "nhụa", "dửng",
            "sờn", "tràu", "diệc", "dỏng", "nông", "đuối", "ngỡ", "da", "khửng", "gái", "thòm", "xẻn", "quyên",
            "đỏm", "su", "nhụng", "tểnh", "gậm", "lẻng", "gài", "kiễng", "nhan", "lốn", "phiến", "rim", "ậng",
            "chỗm", "vẩn", "nghều", "vuốt", "xiêm", "ngại", "phiu", "triền", "coóc", "bóc", "anh", "doa", "nhím",
            "rin", "ngong", "riêng", "vọng", "kép", "khểnh", "khiết", "vái", "ghép", "lủn", "đãi", "diếc", "thải",
            "ngấy", "xoà", "lênh", "bỗ", "hân", "vấu", "nhọt", "tệ", "nhổn", "vánh", "đậu", "ngó", "ủn", "trái",
            "khoặm", "bỏ", "nhất", "lui", "phau", "tội", "mời", "nâng", "chứa", "nắc", "trác", "choái", "bốp",
            "nhủi", "ị", "bòng", "lua", "tạp", "can", "chạp", "xạ", "kịt", "man", "uyên", "toàn", "ngác", "phò",
            "chắt", "vàm", "dài", "thơm", "sạch", "tuồi", "dứa", "đườn", "dịch", "lét", "tú", "siết", "doanh",
            "nhẩm", "vò", "gần", "dướn", "thiêu", "bẻ", "bòn", "hoảnh", "bõ", "nhẩu", "mở", "chây", "liu", "bướu",
            "guộc", "mớn", "nức", "sưu", "hườm", "rêm", "ngột", "hung", "loanh", "lư", "ruột", "tế", "thinh",
            "luôm", "sém", "mịn", "ậm", "nhen", "núm", "hờn", "mỏm", "đắt", "bom", "lươn", "tần", "bác", "khuyên",
            "chuyển", "bêu", "rọi", "phờ", "hoè", "ăng", "trèn", "nổng", "ươm", "nắng", "tất", "ẹo", "nhâng", "có",
            "cọp", "cồn", "nắm", "xóm", "toé", "nhép", "chặn", "loãng", "mội", "xót", "đót", "bẽn", "loang",
            "diễm", "khủng", "sởi", "đới", "riềm", "tong", "tót", "bổi", "trọt", "bờm", "rựa", "thộn", "khai",
            "tạc", "nhẫy", "nhắn", "têm", "thong", "xoàm", "bích", "lù", "thuý", "sầy", "cá", "chăn", "thiến",
            "hẻo", "khuây", "gáy", "béng", "thuỵ", "giựt", "chận", "ô", "hằn", "khé", "sò", "bời", "trình", "yên",
            "ngãng", "tác", "mợ", "mụt", "lõ", "biên", "dớ", "gô", "hàm", "rốt", "quẩy", "văn", "gối", "dâm",
            "tịu", "cỏ", "hổi", "chấn", "nhót", "uy", "mòi", "éo", "lằn", "niêm", "khuynh", "ằng", "hiểm", "rũ",
            "giò", "dử", "trịnh", "phương", "khăm", "sưa", "vòn", "ngan", "xênh", "tấy", "tựa", "tũm", "ỏn", "nha",
            "cọt", "ói", "tành", "xôm", "tỏi", "tẻo", "con", "ngỏn", "vét", "địu", "he", "bún", "ráo", "á",
            "nhuôm", "rướn", "xuể", "vay", "đoành", "ngù", "chập", "nản", "rạo", "phăng", "phoi", "gồm", "sớm",
            "mệnh", "ầng", "ồn", "chưng", "chuôm", "dì", "lộc", "nhom", "ời", "đuỗn", "chồm", "đao", "ùm", "trây",
            "tắn", "xừng", "huý", "ngụ", "thành", "xơi", "hâu", "phân", "nán", "miền", "khứ", "sấm", "ba",
            "nguyệt", "hù", "quẹo", "xoang", "lò", "đòi", "đớp", "quẩn", "hứng", "đậy", "hớm", "chẫm", "giơ",
            "lọi", "kệch", "bụp", "chánh", "giạp", "thiệu", "lạ", "thuồn", "chư", "gờm", "ngờm", "ặc", "suốt",
            "nhí", "rữa", "lặng", "phiện", "thóc", "đắm", "giận", "xề", "yểm", "vấn", "lùa", "thảy", "ngăn",
            "đắng", "bấc", "ơn", "dò", "sật", "nhúc", "phanh", "hòng", "phước", "xộp", "dịu", "sải", "sột", "mồng",
            "lời", "chọi", "rắp", "két", "băm", "chũn", "lom", "him", "ghìm", "nhoáy", "đĩa", "ruỗng", "thẹn",
            "quẩng", "nuông", "mõm", "lắt", "ruồi", "hấp", "lam", "thoà", "thin", "mồn", "ngứa", "nheo", "thỏm",
            "tiu", "sốc", "chẩm", "nhào", "dọc", "dặt", "phủi", "dục", "đĩnh", "trùi", "quỷ", "nập", "phú", "sở",
            "ống", "cải", "đáy", "ga", "huyết", "quách", "chuột", "màng", "giấp", "tở", "hẩm", "kịp", "xép", "hen",
            "dổi", "sờ", "ăn", "chót", "phọt", "ưỡn", "khừng", "khuấy", "rớp", "mia", "bạn", "mê", "dạy", "nghinh",
            "nương", "hoả", "tựu", "hớt", "trạch", "bễ", "bên", "nến", "mị", "tía", "nộm", "vần", "ử", "nạt",
            "xếch", "thình", "ươn", "cói", "khuông", "bầu", "táo", "ì", "hông", "liêng", "du", "xán", "e", "suôn",
            "xạo", "gianh", "đơm", "mộc", "búp", "đởn", "bọng", "lĩ", "làn", "cỡn", "tâng", "suy", "thòi", "chổi",
            "vuột", "xắc", "ven", "tôi", "biếm", "tuếch", "dư", "kinh", "chặm", "dồn", "sửa", "sàng", "đũng",
            "bép", "thủa", "hữu", "chòng", "chổng", "đẽ", "tiệt", "bạng", "bôi", "khốc", "cạm", "miếu", "ngàm",
            "giũa", "bật", "luông", "giác", "thuật", "như", "thụ", "báu", "cà", "chiết", "xẹo", "họp", "bàng",
            "xơm", "tuyến", "mệ", "ngạn", "thể", "bươm", "đặc", "do", "gắt", "lèo", "loa", "tóm", "đuột", "mập",
            "phành", "hôn", "rạc", "đẻ", "lòm", "mũi", "giụa", "tướt", "cức", "miều", "xẩn", "cãi", "nhại", "cót",
            "rời", "vơ", "bạp", "luống", "chẻng", "hảo", "lần", "phềnh", "xê", "gián", "thiền", "vi", "móc", "vêu",
            "khế", "rờn", "gọt", "tộ", "rích", "đón", "thấu", "cồ", "nướu", "tứ", "ngượng", "tủ", "nám", "bẩy",
            "cỡm", "mém", "phệnh", "chuốc", "theo", "phun", "chối", "xổ", "ngụt", "tĩ", "rảng", "chun", "bấm",
            "thật", "nhiệt", "thổ", "ông", "má", "mù", "ngực", "nhiễm", "đờ", "vớt", "ừng", "ngát", "ngậu", "quân",
            "nghiêng", "kẽ", "bày", "léng", "hy", "chè", "thực", "đám", "chò", "khẩm", "luộc", "thôi", "rận",
            "ngoài", "trỗ", "sỗ", "cữ", "dẫu", "lữ", "đời", "muống", "mượt", "vạp", "quắc", "hắng", "hẫng",
            "quành", "ngo", "trầu", "đam", "chùi", "quái", "phàng", "hủi", "kiền", "hóng", "thút", "lộn", "trẹo",
            "cha", "ngóng", "nghện", "đạo", "màn", "loan", "oàm", "cảu", "thắp", "tồng", "tuôn", "rề", "cưới",
            "khêu", "riêu", "xẩm", "ngọng", "nát", "phúc", "đụt", "nhôn", "túi", "mụ", "bặm", "cố", "út", "dơ",
            "đừng", "chờn", "khúc", "nhóp", "xúng", "hãnh", "phông", "mẳn", "xổi", "giằng", "thoang", "mấp",
            "nhắc", "hãn", "thộp", "kiện", "hước", "buýt", "thuộc", "thạp", "cháo", "nạng", "nhao", "giôn", "lào",
            "bao", "nguội", "tiễu", "nhâm", "đùng", "mạch", "viện", "ngỏng", "khục", "thưng", "âm", "sụm", "khiển",
            "miện", "lót", "ngọc", "ềnh", "ví", "đui", "cui", "hởn", "i", "nhạng", "nhốn", "tớp", "sa", "lườn",
            "toen", "cược", "hỉnh", "toại", "chuệnh", "thản", "tuế", "gục", "tởm", "hoạ", "khua", "boóng", "mủi",
            "kén", "đìa", "sắp", "nhiều", "rõ", "ẵm", "khét", "phóc", "đinh", "năn", "chói", "là", "xêu", "sững",
            "chằng", "nết", "trú", "nhãi", "bóp", "xùi", "thẹo", "sên", "phèo", "êm", "nhẽ", "nục", "hiếm", "vẹt",
            "chuộng", "bỡn", "gợi", "ình", "khoét", "khìn", "lốp", "tụt", "phút", "thẳng", "đánh", "mon", "mông",
            "phe", "uẩn", "nung", "thoăn", "van", "ghè", "lạy", "một", "xới", "bệt", "úi", "khốn", "khễnh", "nhuỵ",
            "rán", "địt", "khụ", "lụi", "phạng", "phim", "lược", "xắp", "chấy", "giam", "chĩnh", "ủ", "gôm",
            "truy", "trán", "chai", "rùa", "vọt", "xuồng", "rành", "tổng", "chung", "điểu", "ngộc", "xồ", "lực",
            "rau", "hí", "miệt", "bâng", "mạo", "ngoi", "gá", "kỹ", "chềnh", "nghiễm", "thổn", "bìm", "xun", "xức",
            "lụn", "chửng", "ngường", "gặt", "giám", "dậy", "ngồm", "khoai", "lắp", "bay", "việc", "choạc", "hồ",
            "tĩnh", "di", "ụ", "vận", "nhiệm", "nham", "củi", "tàng", "bin", "cai", "nịch", "xom", "mó", "vầu",
            "hoặc", "thạc", "vao", "sai", "trì", "von", "nhơm", "chầu", "nấu", "đùm", "trứng", "hổn", "quằm",
            "chui", "uôm", "sểnh", "xù", "cỏn", "điêu", "bia", "mẫu", "nự", "thân", "toan", "khướt", "bảy", "kho",
            "ngúng", "tợn", "thử", "lõi", "bưởng", "hử", "hống", "nhỉ", "loạn", "trộn", "thoai", "tẩy", "tho",
            "choang", "đười", "bon", "chiến", "phục", "xồng", "mỗ", "bởi", "tuông", "xắt", "xâu", "bảo", "bím",
            "xáo", "đội", "cò", "hôm", "giùm", "thãi", "nữa", "dai", "nhóm", "hệ", "cực", "top", "nhếu", "gộc",
            "giuộc", "vâng", "giáo", "chạch", "xẩu", "hếch", "vả", "liều", "ngún", "chuếnh", "luẩn", "lớp",
            "huynh", "trộng", "thoát", "nhuốc", "say", "ganh", "sao", "hèo", "sã", "bèm", "lường", "thiển",
            "xướng", "xọp", "lẳn", "bẽ", "ngái", "nháng", "niễng", "toang", "ngoặc", "quèo", "xang", "uyển", "sơ",
            "dúng", "gầm", "bệu", "dẳng", "bửa", "ngợ", "gieo", "khủ", "tróc", "mọ", "chùm", "nệm", "đụp", "kĩ",
            "nhả", "tốc", "tào", "dốc", "cấy", "phía", "thảo", "rưng", "lé", "ỉu", "xương", "choàng", "xám",
            "mắng", "mẽ", "nhẹm", "quệ", "nùng", "tược", "rướm", "đồm", "mướn", "xí", "nguýt", "gion", "dông",
            "chuộc", "đênh", "nỡm", "hả", "chiu", "sả", "bỡ", "ầm", "cưng", "chạm", "khới", "lội", "vài", "muốt",
            "vượng", "trớn", "liệu", "nhức", "lợm", "hịch", "trứ", "nhồi", "gặng", "gù", "tèo", "dạn", "ộp",
            "ngủng", "nhong", "tiếng", "mén", "gòn", "bưu", "căn", "đớt", "héo", "oắt", "rượi", "gánh", "phắp",
            "lài", "nhòng", "tươm", "đó", "nhồn", "biền", "khệ", "mỏi", "người", "nà", "sài", "đây", "vảnh",
            "nhụi", "triều", "đóng", "này", "xẩy", "hiêng", "chịt", "ý", "khành", "tham", "mắm", "xoải", "xế",
            "dễ", "khư", "ngăm", "sậm", "xã", "lồn", "cười", "ngủm", "lức", "gũi", "đon", "khách", "nhơi", "đìu",
            "cợn", "gạ", "ne", "khản", "khinh", "tạt", "im", "khúm", "hùm", "cụm", "xổm", "thừng", "nhờn", "thám",
            "nậu", "thun", "xỉn", "khà", "moi", "tắp", "luyện", "nhèo", "tưới", "mục", "ghé", "xa", "chẹt", "vĩ",
            "mép", "bẻm", "thiều", "dấp", "ạ", "cộng", "nhưng", "giồng", "vếu", "ngoảy", "chứ", "lụng", "à",
            "song", "tố", "bấp", "hiếng", "căng", "phẩm", "vòm", "moóc", "ngang", "ngộp", "tuýp", "duy", "quẹt",
            "thẩm", "dềnh", "nhảy", "khạo", "đọt", "ngôi", "huỷ", "máu", "vâm", "nẻ", "thọc", "nhoét", "chiếm",
            "nghĩa", "rạch", "danh", "bùa", "đểnh", "nhún", "nhừ", "phỡn", "thận", "năm", "đấy", "nhẵng", "nhi",
            "luyn", "thuồng", "khăn", "tàn", "ợt", "nhổ", "chần", "quặc", "vá", "rã", "trời", "ùa", "phụng", "vo",
            "khát", "ngoắt", "thoả", "lập", "đốm", "khều", "ngóm", "thẻ", "ria", "lại", "lầm", "vạ", "dỗi",
            "quàng", "sấy", "ăm", "truỵ", "cúng", "hiệu", "khối", "ngót", "lan", "lãnh", "khật", "xăn", "chế",
            "nhái", "oại", "chông", "ngoan", "quặn", "náy", "a", "quềnh", "các", "xiết", "niệt", "láp", "hèn",
            "đống", "thững", "ướt", "từa", "vỏ", "chống", "ré", "dẹp", "rền", "ngẩng", "tôn", "duốc", "góp",
            "liệng", "răng", "lọn", "ứa", "mẫn", "gin", "ngạo", "khôi", "đoàn", "hẹ", "rịa", "ngòm", "cún",
            "khuỳnh", "chịu", "đài", "vều", "điền", "quên", "già", "hò", "hút", "lễ", "rãnh", "nột", "hủn", "nín",
            "đác", "chin", "giâu", "ty", "nhử", "nhọc", "xắng", "đụng", "hạn", "nhặt", "giản", "sòm", "chuồng",
            "sấn", "râu", "hỗm", "triệu", "xầm", "xự", "sót", "luyến", "tốt", "nháo", "lải", "nghèo", "cập", "leo",
            "phấn", "khoăn", "choáng", "giời", "cát", "vứt", "lèm", "chùn", "sếp", "ngỏ", "ấu", "cây", "thon",
            "táu", "xải", "cạo", "bừ", "bắn", "xút", "ngợi", "hằm", "cấn", "đẩn", "địch", "chuyến", "dẳn", "ngoạn",
            "nêu", "choại", "phết", "hãng", "rảo", "gièm", "truồng", "rấm", "an", "hô", "kem", "bứa", "mĩm",
            "xuống", "hau", "đoái", "vố", "máy", "vẩy", "nái", "hoay", "quát", "sỏi", "thù", "gồng", "vụ", "dôi",
            "gây", "gớm", "thẩu", "nính", "lung", "cái", "lìm", "choẹ", "huênh", "mùn", "kệnh", "nhàu", "khệnh",
            "ẻn", "chỉn", "thuyên", "đói", "túp", "cảnh", "chơi", "khóc", "lảm", "truân", "ruổi", "dìu", "thần",
            "tọng", "úc", "đào", "gò", "dân", "ván", "giội", "hài", "lết", "xé", "chim", "lố", "giòn", "thiên",
            "lổ", "gẫu", "xua", "ngoa", "lộ", "đệp", "bạ", "dết", "khiệng", "cổng", "bằm", "mãn", "giối", "tận",
            "chau", "ngách", "diễn", "giặc", "phẫn", "hơn", "mặt", "luật", "đàn", "lạn", "thống", "nhoay", "xụi",
            "dã", "thá", "thều", "chã", "kém", "lén", "ngoẻo", "toong", "bái", "quỹ", "cỡ", "sựt", "rết", "hộ",
            "bính", "rọt", "són", "sừn", "bận", "dúm", "tốn", "vin", "nhặn", "nếu", "muối", "chạy", "nữ", "the",
            "reng", "đầy", "chân", "chếch", "ánh", "bồn", "sậu", "tao", "gặn", "sạo", "chướng", "nguỵ", "rấp",
            "bữa", "gia", "béo", "binh", "kiềng", "lưỡi", "mấn", "hẳm", "vửng", "rum", "dẫy", "thím", "vội", "đẵn",
            "rắc", "hoánh", "khẽ", "én", "giậu", "tháng", "nhạo", "chộp", "khuâng", "chồn", "chạo", "nghễu",
            "ngọt", "chựng", "ngáo", "thèm", "muồng", "lượm", "khấp", "nguyền", "trố", "nhện", "trùng", "ghẻ",
            "khoé", "hoẵng", "ục", "nè", "tụng", "chạ", "thỉu", "mành", "kê", "khiến", "dâu", "ân", "tiên", "sè",
            "dãy", "cáng", "tệp", "nối", "hèm", "niết", "phạch", "bè", "cự", "tạ", "bu", "xuyên", "thiếu", "dậu",
            "miểng", "hoa", "ngơn", "máng", "trốn", "ám", "xờm", "rinh", "ọc", "dua", "hề", "uể", "thậm", "guồng",
            "nhúm", "phá", "rịt", "hoá", "xo", "khói", "vược", "kẻo", "mún", "họ", "khịt", "lon", "tủa", "dật",
            "ngổ", "rẻo", "nghẹ", "tủi", "gại", "đảng", "chộn", "ái", "búa", "ộc", "khoảnh", "gộp", "đước", "nài",
            "hức", "xáng", "nhiễn", "nống", "rần", "huân", "đồ", "hừng", "bịch", "nành", "nghĩ", "nhủng", "cứ",
            "trệ", "quạ", "rật", "đếch", "rú", "khớ", "quẫn", "đâm", "neo", "nghịt", "muỗi", "trị", "quai", "cán",
            "đắc", "phớ", "đản", "tí", "vắng", "xềm", "tuyền", "lụp", "vương", "hoáy", "loạt", "thoảng", "chiêm",
            "đoàng", "tha", "hỗ", "néo", "ruộng", "sậy", "hực", "goá", "thức", "sạ", "khanh", "thót", "giề", "tỉm",
            "được", "khấu", "ruồng", "dặm", "dại", "xích", "ngoét", "hướng", "trốt", "uốn", "bổng", "tưởng",
            "nhía", "đỗ", "nhẹ", "chù", "giành", "thẻo", "nhói", "nháy", "nhóc", "chẫu", "dấu", "chóp", "nhạn",
            "tới", "nhùng", "nhởi", "niềm", "phều", "gioi", "thoi", "hé", "dích", "huyện", "nhểu", "rên", "vồ",
            "cáy", "thìn", "đọ", "thác", "thấm", "sọ", "chíu", "xăng", "chú", "đan", "phạc", "hua", "lẽ", "vèo",
            "lủ", "gả", "nhăn", "đử", "chắc", "lồ", "tam", "núc", "trấn", "bối", "rửng", "trông", "chết", "ngần",
            "coi", "quắn", "cú", "mệt", "chín", "mật", "gầy", "kiên", "rầy", "nhiêu", "nổ", "trườn", "bế", "biếu",
            "ừ", "thảng", "xoạch", "lợp", "ảm", "nạc", "quỳ", "năng", "thế", "thái", "bánh", "chẩn", "linh", "dẹo",
            "men", "cơn", "khảnh", "bĩu", "lóp", "bôm", "hầy", "thừ", "hơi", "án", "dúa", "ùn", "đôi", "phéng",
            "un", "thở", "tớ", "bì", "ệ", "đọng", "quẽ", "thóp", "triết", "nèo", "í", "tuân", "lả", "lông", "xấc",
            "bót", "khoá", "viết", "cỡi", "ước", "cũ", "phắc", "ang", "phu", "rẽ", "cờn", "thối", "thắm", "tậm",
            "mạnh", "rộ", "hoán", "chẩu", "ngự", "đoản", "dừa", "mớ", "khích", "giãy", "mới", "nực", "giảm",
            "liến", "lách", "dứng", "váng", "rục", "tráng", "phụ", "tẹp", "sát", "diệu", "dây", "hểnh", "cúp",
            "lối", "phịch", "liễn", "luộm", "đạch", "cun", "trẽn", "xoe", "phính", "lâng", "chểnh", "lăn", "trỏ",
            "cừ", "trường", "đoan", "soài", "quy", "ót", "nguây", "bùi", "vút", "hoàng", "đẩu", "ườn", "khắt",
            "róng", "lọ", "chực", "phây", "rưới", "ngẩn", "duyệt", "cuộng", "màu", "xoan", "nao", "bở", "khiếm",
            "rụi", "ê", "liệt", "kèo", "thượt", "kháng", "bưng", "vệ", "lôi", "giăm", "phượng", "vỏng", "han",
            "vợt", "tát", "khòm", "tuồng", "khóm", "pheo", "cảng", "tắm", "đích", "nhát", "quàn", "hầm", "hụi",
            "sửng", "chụm", "quản", "hấn", "dồ", "oi", "sổ", "tròng", "hun", "quạng", "tù", "hùn", "phứa", "xon",
            "dê", "chắn", "bám", "rui", "nhang", "thăn", "lưỡng", "nhinh", "nốt", "kết", "cạu", "môi", "ngậm",
            "ngừ", "ú", "ách", "tẽ", "thịt", "bện", "tưởi", "đổng", "nạp", "chuyện", "rút", "bập", "kin", "khoát",
            "gien", "lững", "ủa", "xuề", "sú", "giáng", "lũm", "ém", "lít", "com", "côm", "bủn", "loạc", "lợt",
            "nướng", "ròng", "nàn", "inh", "đã", "mối", "sình", "rủng", "tiểu", "coong", "dâng", "tịch", "thuốn",
            "giêng", "choòng", "thuở", "rà", "cừu", "tờ", "boong", "chóc", "vẻn", "quét", "ngồ", "biển", "rô",
            "xinh", "chon", "chớn", "đẩy", "giong", "dùi", "ngửi", "huyền", "nhõng", "nóp", "xuộm", "phịu", "úa",
            "độp", "ễnh", "thằng", "họng", "sáu", "hỡi", "ớt", "láo", "nhầm", "đảm", "mỏ", "chưa", "rọ", "quyệt",
            "thôn", "dỏ", "ghệt", "rạm", "cận", "thây", "au", "ớn", "nguy", "chện", "chắm", "ngoao", "thiếp",
            "hởi", "bình", "chòm", "túm", "nắp", "oan", "cầu", "khưỡng", "nhài", "đáo", "dỗ", "chà", "ná", "ngẵng",
            "sum", "sỉ", "đúm", "lý", "doạ", "chìm", "tiệm", "hồi", "hắt", "khái", "trót", "ngay", "phải", "đuốc",
            "giọt", "nỏ", "hòi", "rảu", "cum", "quặm", "thó", "nhắm", "thọt", "tréo", "nhét", "sảng", "sỉa", "gỗ",
            "vung", "rằng", "nhộn", "mói", "tỉ", "tò", "dợ", "nạ", "âu", "gõ", "rờm", "hiếu", "xoen", "rảnh",
            "lỡm", "ngoác", "sách", "văng", "ó", "nhồm", "mí", "kim", "cổ", "điếm", "oăm", "liêu", "biết", "bẹn",
            "trắc", "nồm", "nàng", "bả", "mày", "sắn", "dệch", "ỡm", "quay", "vặc", "véo", "liểng", "dảnh", "sõi",
            "lạu", "ngà", "oản", "khéo", "hóm", "tọp", "ai", "bột", "khướu", "điện", "bụt", "nọn", "thúi", "nguồn",
            "tre", "mứu", "đòng", "mì", "lái", "nhúi", "cốt", "cỗi", "quyện", "trét", "dòng", "bảu", "choãi",
            "nòm", "hội", "rạ", "sòng", "xe", "tóp", "hóc", "khảy", "vụng", "biệt", "khổng", "sin", "tám", "dũi",
            "chúng", "cắp", "kệ", "khảng", "nớp", "nồi", "bĩnh", "toèn", "nhứ", "mỗi", "tấn", "thủm", "lừa",
            "vãng", "tợp", "tùm", "xớ", "lẽo", "khươi", "nợp", "ngoáy", "vông", "rộn", "vằng", "ngấc", "chọn",
            "lềnh", "xiểng", "phề", "khất", "dẻ", "gán", "tuốt", "bẹt", "dợm", "le", "cóp", "tím", "dơn", "lạm",
            "nghênh", "mưu", "sắt", "ỷ", "nhẹo", "khò", "đạt", "quần", "trung", "hoạn", "ngủi", "hũm", "chình",
            "cốp", "ngấn", "trĩnh", "trách", "đắn", "hánh", "khịa", "nghẽo", "thốc", "nhãng", "vong", "nạnh", "xà",
            "mạng", "xoay", "bấy", "oạp", "bào", "ngẫu", "hăm", "đắp", "chuỳ", "gấp", "dong", "dan", "bợt", "rỏi",
            "ớm", "hụp", "thụp", "ngông", "hạp", "nợ", "toàng", "ghề", "giọng", "loạng", "sử", "ngoen", "uế",
            "nhủn", "sịa", "dầm", "dao", "lồi", "tặc", "sì", "đơ", "nhàm", "hà", "hát", "thả", "riệt", "kẹp",
            "gâu", "vua", "vượt", "ngáng", "nhích", "bèo", "nhìn", "giúp", "xả", "choán", "ró", "đà", "dồng",
            "đấm", "xít", "cờ", "nguyện", "khe", "lợn", "mu", "dọn", "làu", "soạt", "trụ", "thanh", "thùng", "mao",
            "tử", "bụi", "lấn", "mẹo", "loăng", "phai", "ấy", "nghê", "mọt", "nắn", "nghêu", "rởm", "tường", "vực",
            "búng", "nhản", "khàn", "vụn", "đường", "lem", "thờn", "xốp", "hót", "phưng", "tớn", "lẳng", "chao",
            "cúi", "toét", "ngã", "trê", "đòn", "rượu", "hỏm", "mai", "bắp", "tòm", "muốn", "phím", "rua", "cấu",
            "tuẫn", "khẳn", "loáng", "thuần", "oẹ", "kễnh", "mậm", "dấm", "đấng", "đưa", "toi", "thoắng", "thích",
            "chờ", "hạc", "vẹm", "gụ", "sù", "nhòm", "xốt", "dằn", "thênh", "truật", "thau", "xếp", "mửng", "rụm",
            "đỉa", "ẩu", "oành", "khởi", "tút", "sều", "khớp", "thiểu", "tãi", "vệt", "dùn", "chẵn", "giãi",
            "còng", "dạng", "nhô", "gao", "lười", "kẽm", "cuồng", "khụt", "ráu", "úm", "quắt", "ngoẹo", "thùa",
            "khựng", "oanh", "gí", "hứa", "kềnh", "nửa", "trẩy", "ỉ", "mố", "hưng", "thương", "rườm", "hủ",
            "ngoáo", "nũng", "giếc", "lùi", "chị", "dái", "hếu", "teo", "thẽ", "đê", "khuyến", "khổ", "ngoảnh",
            "hôi", "xoè", "kháo", "kham", "bịn", "om", "giủi", "ắng", "sui", "mịt", "bồm", "phốt", "xuyến", "lảo",
            "ngốc", "khú", "phó", "cáo", "léo", "dớp", "đàm", "hẹn", "quỵt", "trạm", "chèm", "chụt", "hụt", "xui",
            "đủng", "u", "ngụp", "lẩu", "dày", "vôi", "bậm", "đút", "huề", "cắn", "sưng", "nấm", "lọt", "xôn",
            "nhưỡng", "thuôn", "chạng", "bẹ", "quơ", "thự", "vặt", "thết", "khự", "khằng", "mườn", "chay", "vai",
            "đãng", "dòm", "hình", "mổ", "dăm", "ghịt", "choe", "vặn", "húc", "cù", "hào", "tủn", "rịn", "díp",
            "sịt", "thiệp", "nghiêm", "rương", "lỉnh", "o", "chỗ", "nho", "sảnh", "ngoải", "yết", "dạc", "nuôi",
            "khoen", "nai", "xung", "đành", "ngáp", "ham", "vỏn", "lếch", "bớp", "ghen", "mũ", "nhũ", "khoan",
            "phúng", "hoác", "tròn", "vì", "nhột", "chật", "chùa", "bét", "tầy", "soát", "hươu", "nhoai", "rẻng",
            "gam", "cướp", "đốp", "ngục", "dăn", "ghém", "xuôi", "cửu", "sư", "giáp", "bẫy", "ờ", "sá", "ton",
            "tấu", "nhĩ", "oán", "tòi", "tản", "xẵng", "chừa", "ngầu", "ghiếc", "kíp", "buôn", "gìn", "nhút", "tả",
            "ngài", "cạy", "nhoe", "ngựa", "rặt", "rằn", "mưng", "ắp", "suông", "mím", "mong", "chat", "ngược",
            "viêm", "hất", "buột", "bâu", "vắt", "chệnh", "lũi", "sằng", "hiếp", "san", "thề", "xoạc", "trả",
            "toạng", "ngưng", "dướng", "vởn", "tỷ", "phôn", "ngu", "đì", "hoại", "ngoằn", "xoăn", "dầu", "hoang",
            "nóc", "lu", "đáng", "lườm", "thường", "ngỏm", "loại", "chốn", "lờm", "xằng", "sự", "trẹ", "choắt",
            "mèm", "tắt", "hợt", "gót", "giã", "gờ", "súc", "sạm", "xóc", "sốt", "vàn", "xuýt", "chủng", "vạy",
            "chèn", "kên", "chôn", "èo", "dấn", "đéo", "bề", "nhầu", "toát", "đun", "gắp", "nhẹn", "mắn", "mướt",
            "mú", "đựng", "cóc", "tắc", "ngoay", "chột", "ngấp", "phởn", "ròn", "trẹt", "ngạc", "tuềnh", "bén",
            "đũi", "tạch", "sán", "nhược", "siêng", "với", "vợ", "lích", "lộng", "càn", "lẻn", "não", "hục",
            "ngút", "thủi", "mân", "thông", "bông", "nghiện", "vồng", "ong", "lâm", "trít", "cày", "gom", "xoã",
            "thồ", "nhon", "nhằn", "chụp", "nhồng", "nghẽn", "nhùn", "rụt", "chải", "nẹt", "rêu", "hổm", "kếp",
            "bủa", "méo", "miễn", "cằm", "quặp", "vạc", "vía", "mào", "lì", "nghỉnh", "sông", "ngất", "dạt", "đỏi",
            "ngời", "tịnh", "đừ", "tượt", "cua", "lảu", "bủ", "quận", "xanh", "xớn", "nhơ", "lịm", "hang", "giát",
            "trừng", "té", "ẹp", "xìa", "roi", "răn", "vắn", "kính", "trượng", "sức", "kềm", "khom", "queo", "lự",
        ]

        self.others = [
            "0", "1", "2", "3", "4", "5", "6",
            "7", "8", "9", "!", "@", "#", "$",
            "%", "^", "&", "*", "(", ")", "'",
            "\"", "-", "=", "[", "]", "{", "}",
            "|", "\\", ":", ";", "<", ">", "/",
            "?", ".", ",", "_", "。", "·",

            # Vietnamese lowercase letters (vowels with every tone mark, plus consonants and
            # a few foreign-loanword letters) used by the tokenizer's character-level fallback
            # for tokens that are not Vietnamese syllables. Letters that already appear in
            # self.morphemes as standalone one-letter words (a, e, i, o, u, y, ơ, ư and their
            # toned forms) are left out here so each token keeps a single, unambiguous id.
            "ă", "ằ", "ắ", "ẳ", "ẵ", "ặ", "â", "ầ", "ấ", "ẩ", "ẫ", "ậ",
            "ẻ", "ẽ", "ể", "ễ", "ò", "ỏ", "õ", "ỗ", "ỡ", "ũ", "ữ", "ự",
            "ỳ", "ỹ", "ỵ", "b", "c", "d", "đ", "g", "h", "k", "l", "m",
            "n", "p", "q", "r", "s", "t", "v", "x", "f", "j", "w", "z"
        ]

        vocab = self.morphemes + self.others
        self.id2label = {idx: token for idx, token in enumerate(self.specials + vocab)}
        self.label2id = {token: idx for idx, token in enumerate(self.specials + vocab)}

        self.vocab_size = len(self.label2id)
